kanak227/NGO-WEBSITE

causes.html, contact.html, donation.HTML, events.html, index2.html, news.html
Added navbar to all the pages of the website 
Fixes #13
=> Issue #13  solved

index.html, login.html, register.html, styles.css
Made the Login and the Register Pages
Fixes #3
=> Issue #3  Solved

contact.html
Added real-time validation for the contact form to prevent numbers in the name field and ensure correct email format.
Fixes #5 
https://github.com/user-attachments/assets/3f03855c-ed41-4982-8a73-71080b70f18f
=> Added real-time validation for contact form

causes.html, contact.html, donation.HTML, events.html, news.html
ADDED THE NAVBAR THAT LOOKS ALIKE IN ALL THE PAGES
ADDED THE NAVBAR THAT LOOKS ALIKE IN ALL THE PAGES
Fixes #24
=> ISSUE #24 SOLVED

causes.html, contact.html, events.html, index.html, news.html
Added footer with proper links in the website.
Fixes #11
=> Updated with properly assigned links in footer

styles.css
=> Enhnaced navbar

MIT License.md
Fixes #37 
- [ yes] New feature ✨
- [yes ] Documentation update 📖
Please merge my pull request
@kanak227
=> Create MIT License.md

index.html, styles/styles.css
Add resposiveness  to the website  (width:768px)
Fixes #1 
- [✅ ] New feature ✨
- [✅ ] My code follows the project's coding standards.
- [ ✅] I have tested my changes and verified they work as intended.
- [ ✅] I have added relevant documentation (if applicable).
- [ ✅] My changes do not introduce new warnings or errors.
=> Add responsiveness to website

index.html, pages/donation.HTML
Fixed the Button and text miss alignment issue .
Fixes #65
- [✅ ] Bug fix 🐛
- [✅ ] My code follows the project's coding standards.
- [✅ ] I have tested my changes and verified they work as intended.
- [✅ ] My changes do not introduce new warnings or errors.
NA
=> Issue no #65 [Bug]: Donate now button position fix along with 404 error fixing.

app.js, index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/index2.html, pages/login.html, pages/news.html, pages/register.html, styles/styles.css
This PR fixes the overflow bug in the Navbar, footer was already responsive though. Also added sticky navbar to all the pages
Fixes #54 
Fixes #74  
https://github.com/user-attachments/assets/9645fa87-c9fa-40ca-a4ad-d18f43fe6cba
=> Navbar Bug

404.html, index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html, pages/register.html
This PR adds meaningfully content in all the pages of this website, which improves overall user experience.
Fixes #62
=> Replaced All Lorem Ipsum with meaningfull content

pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html
📝 Pull Request: Added Back-to-Top Button to All Pages
📌 Description
This PR adds a Back-to-Top button on all pages of the NGO website, allowing users to quickly scroll back to the top.
Fixes #91
🔍 Type of Change
Bug fix 🐛
✅ Checklist
My code follows the project's coding standards.
I have tested my changes and verified they work as intended.
I have added relevant documentation (if applicable).
My changes do not introduce new warnings or errors.
🖼️ Screenshots
=> Added Bact-to-Top button to all pages

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html
=> Solved the contact info issue

pages/news.html, styles/news.css
improved the UI of news section.
Fixes #76 
- [✅ ] New feature ✨
- [✅ ] My code follows the project's coding standards.
- [✅ ] I have tested my changes and verified they work as intended.
- [✅ ] I have added relevant documentation (if applicable).
- [✅ ] My changes do not introduce new warnings or errors.
- improve the UI and fixes the bug due to which card1 is rendering correctly 
- highlight the tag 
-given border radius to image to make it merged
-added some hover effects
=> improved the ui and some function in news page

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html, styles/styles.css
added logo  redirection to the homepage
Fixes #110
=> added logo redirect

pages/donation.HTML
Added footer to donation page
Fixes #108
=> Added the Footer to donation page

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html
Replaced the logo of twitter with its new one
Fixes #111
=> replaced the logo of twitter with its new one

404.html
=> Added proper ARIA attributes to SVG elements for screen reader compatability

index.html, styles/styles.css
This PR makes the whole page responsive across all screen breakpoints
Fixes #116 
I have changed all hard coded units to responsive units and proper conterisation of all the components has been done.
=> Home Page made Responsive

404.html
=> Made error 404 responsive

pages/login.html, pages/register.html, styles/login.css, styles/register.css
Implemented Firebase authentication for login and sign-up functionality, including email/password and Google login. Enhanced secure session management and user profile handling.
Fixes #121 
Add your own API keys for the required changes. For security reasons I can't provide my own APIs.
=> Added Firebase Authentication

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html, styles/styles.css
Added lazy-loading to images
Fixes #128
=> Lazyloading

pages/contact.html, pages/news.html
This PR will fix the logo issue on contact page.
Fixes #(issue number)
#136 has been resolved.
=> Fix logo issue on contact page

index.html, styles/contact.css, styles/styles.css
=> minor issues fixed

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html, styles/styles.css
Solved Issue :  143
Description : Enhancement of UI of the Navbar in ( Responsive Form )
Fixes #143 
🔍 Type of Change
🖼️ Screenshots
https://github.com/user-attachments/assets/68894f00-907d-4489-90a7-6ff031bda755
=> Solved #143

styles/styles.css
=> improved css

styles/causes.css, styles/contact.css, styles/donation.css, styles/events.css, styles/login.css, styles/news.css, styles/register.css, styles/styles.css
=> generalized animation timings and colour generalized

styles/causes.css, styles/contact.css, styles/donation.css, styles/events.css, styles/login.css, styles/news.css, styles/register.css, styles/styles.css
=> focus styles

index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/news.html, styles/causes.css, styles/contact.css, styles/donation.css, styles/events.css, styles/login.css, styles/news.css, styles/register.css, styles/styles.css
=> dynamic footer

index.html, styles/news.css, styles/styles.css
=> Changes made

pages/login.html, styles/login.css, styles/styles.css
fixed image and space b/w texts
Fixes #171
=> Hero Section

app.js, index.html, pages/causes.html, pages/contact.html, pages/donation.HTML, pages/events.html, pages/login.html, pages/news.html, pages/register.html, styles/causes.css, styles/contact.css, styles/donation.css, styles/events.css, styles/login.css, styles/news.css, styles/register.css, styles/styles.css
This feature introduces a dark theme to enhance the user experience. It includes:
- A toggle button to switch between light and dark modes.
- Persistent theme preference using localStorage.
- Updated styles for backgrounds, texts, inputs, cards, and other UI elements using CSS variables.
Fixes #122 
https://drive.google.com/file/d/1nOi1dSDLQJbdG4ktnB0ONd53EdClRv3S/view?usp=sharing
=> Implement Dark Theme

index.html, pages/eventRegister.html, pages/events.html, styles/eventRegister.css, styles/styles.css, validation.js
Added a form for registering in events
Fixes #189
=> Created the Event Register Page

index.html, styles/styles.css
Corrected the padding of the image and other paddings of the div
Fixes #186
=> Corrected padding

index.html, styles/styles.css
1. Enhanced the **Events section** with an improved, responsive UI.
2. Refactored inline CSS from `index.html` to `styles.css` for better maintainability.
Fixes #163
=> enhance events cards

index.html, pages/donation.HTML, styles/styles.css
=> Added newsletter in home page and donation page

index.html, pages/donation.HTML, pages/eventRegister.html, pages/events.html, styles/eventRegister.css, styles/styles.css
=> Event register

README.md
=> Add the video in the readme file

pages/eventRegister.html, styles/eventRegister.css
=> Added dark mode

pages/about.html, styles/about.css
=> Added return to home, enhanced text, added hover

pages/causes.html, styles/causes.css
Improve the causes section
Fixes #227
Enhance the hover effect on the image
Improve the progress bar
improve the food and water badge
improve the learn more button
Enhance the hover effect of the cards
=> Improve the causes section
